// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoI7G7foqcsI-gNZD5LEXc9sfU2X0ONEc',
    appId: '1:984056689373:web:b37fb6720dc2e00b6ca134',
    messagingSenderId: '984056689373',
    projectId: 'hotel-booking-b1d5c',
    authDomain: 'hotel-booking-b1d5c.firebaseapp.com',
    storageBucket: 'hotel-booking-b1d5c.appspot.com',
    measurementId: 'G-18PGEFWN2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqQnakHjW4u-aJOU4ODpOuwPp_GRxksZI',
    appId: '1:984056689373:android:e925431f18c914176ca134',
    messagingSenderId: '984056689373',
    projectId: 'hotel-booking-b1d5c',
    storageBucket: 'hotel-booking-b1d5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBATSq_qC10L50qfBB_HxgB08sUyvwRiLM',
    appId: '1:984056689373:ios:337dd29e45f9ceea6ca134',
    messagingSenderId: '984056689373',
    projectId: 'hotel-booking-b1d5c',
    storageBucket: 'hotel-booking-b1d5c.appspot.com',
    iosBundleId: 'com.solinovation.hotelbooking',
  );
}
